<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AdsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('ad')->truncate();
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('ad')->insert([
            // Real estate ads
            [
                'title' => 'Luxury Apartment for Rent',
                'type' => '1',
                'approved' => 1,
                'show_count' => 100,
                'description' => 'A beautiful luxury apartment in the heart of the city.',
                'price' => 2000,
                'discount' => null,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '37.7749',
                'lng' => '-122.4194',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'luxury_apartment.jpg',
            ],
            [
                'title' => 'Modern House for Sale',
                'type' => '1',
                'approved' => 1,
                'show_count' => 50,
                'description' => 'A modern house located in a quiet neighborhood.',
                'price' => 500000,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '40.7128',
                'lng' => '-74.0060',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'modern_house.jpg',
            ],
            [
                'title' => 'Cozy Cottage for Sale',
                'type' => '1',
                'approved' => 1,
                'show_count' => 60,
                'description' => 'Charming cottage in a serene setting, perfect for a weekend getaway.',
                'price' => 300000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '36.1699',
                'lng' => '-115.1398',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'cozy_cottage.jpg',
            ],
            [
                'title' => 'Penthouse with Ocean View',
                'type' => '1',
                'approved' => 1,
                'show_count' => 70,
                'description' => 'Exclusive penthouse with stunning ocean views.',
                'price' => 3500,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '34.0522',
                'lng' => '-118.2437',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'penthouse.jpg',
            ],
            [
                'title' => 'Spacious Family Home',
                'type' => '1',
                'approved' => 1,
                'show_count' => 30,
                'description' => 'A spacious family home with a large backyard.',
                'price' => 450000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '39.7392',
                'lng' => '-104.9903',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'family_home.jpg',
            ],
            [
                'title' => 'Chic Studio Apartment',
                'type' => '1',
                'approved' => 1,
                'show_count' => 80,
                'description' => 'Stylish studio apartment in a vibrant neighborhood.',
                'price' => 1500,
                'discount' => null,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '41.8781',
                'lng' => '-87.6298',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'studio_apartment.jpg',
            ],
            [
                'title' => 'Beautiful Farmhouse',
                'type' => '1',
                'approved' => 1,
                'show_count' => 20,
                'description' => 'A stunning farmhouse with a large plot of land.',
                'price' => 400000,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '35.682839',
                'lng' => '139.759455',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'farmhouse.jpg',
            ],
            [
                'title' => 'Quaint Bungalow',
                'type' => '1',
                'approved' => 1,
                'show_count' => 40,
                'description' => 'A quaint bungalow perfect for small families.',
                'price' => 250000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '33.4484',
                'lng' => '-112.0740',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'bungalow.jpg',
            ],
            [
                'title' => 'Elegant Condo for Sale',
                'type' => '1',
                'approved' => 1,
                'show_count' => 90,
                'description' => 'An elegant condo with modern finishes.',
                'price' => 300000,
                'discount' => 0.07,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '47.6062',
                'lng' => '-122.3321',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'elegant_condo.jpg',
            ],
            [
                'title' => 'Riverside Villa',
                'type' => '1',
                'approved' => 1,
                'show_count' => 15,
                'description' => 'A beautiful villa located by the riverside.',
                'price' => 600000,
                'discount' => 0.15,
                'active' => 1,
                'category_id' => 4,
                'status' => 1,
                'paid' => 0,
                'lat' => '42.3601',
                'lng' => '-71.0589',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'riverside_villa.jpg',
            ],

            // Car ads
            [
                'title' => '2019 Honda Civic for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 75,
                'description' => 'A well-maintained 2019 Honda Civic with low mileage.',
                'price' => 22000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '34.0522',
                'lng' => '-118.2437',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'honda_civic.jpg',
            ],
            [
                'title' => '2020 Tesla Model 3 for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 40,
                'description' => 'A top-of-the-line Tesla Model 3 with autopilot features.',
                'price' => 35000,
                'discount' => 0.08,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '36.1699',
                'lng' => '-115.1398',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'tesla_model3.jpg',
            ],
            [
                'title' => '2018 Ford F-150 for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 55,
                'description' => 'A powerful 2018 Ford F-150 in excellent condition.',
                'price' => 30000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '30.2672',
                'lng' => '-97.7431',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'ford_f150.jpg',
            ],
            [
                'title' => '2021 BMW 3 Series for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 30,
                'description' => 'A luxurious 2021 BMW 3 Series with all the features.',
                'price' => 45000,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '40.7608',
                'lng' => '-111.8910',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'bmw_3_series.jpg',
            ],
            [
                'title' => '2015 Chevrolet Silverado for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 20,
                'description' => 'Reliable 2015 Chevrolet Silverado, perfect for work and play.',
                'price' => 25000,
                'discount' => null,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '39.7392',
                'lng' => '-104.9903',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'chevrolet_silverado.jpg',
            ],
            [
                'title' => '2017 Toyota Camry for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 35,
                'description' => 'A reliable 2017 Toyota Camry with great mileage.',
                'price' => 18000,
                'discount' => 0.05,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '42.3314',
                'lng' => '-83.0458',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'toyota_camry.jpg',
            ],
            [
                'title' => '2020 Nissan Altima for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 25,
                'description' => 'A stylish 2020 Nissan Altima with low mileage.',
                'price' => 23000,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '33.4484',
                'lng' => '-112.0740',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'nissan_altima.jpg',
            ],
            [
                'title' => '2022 Hyundai Sonata for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 10,
                'description' => 'A brand new 2022 Hyundai Sonata with advanced features.',
                'price' => 27000,
                'discount' => null,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '39.7392',
                'lng' => '-104.9903',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'hyundai_sonata.jpg',
            ],
            [
                'title' => '2021 Kia Forte for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 5,
                'description' => 'A reliable and efficient 2021 Kia Forte.',
                'price' => 21000,
                'discount' => 0.1,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '40.4406',
                'lng' => '-79.9959',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'kia_forte.jpg',
            ],
            [
                'title' => '2016 Subaru Outback for Sale',
                'type' => '2',
                'approved' => 1,
                'show_count' => 12,
                'description' => 'A versatile 2016 Subaru Outback, great for outdoor adventures.',
                'price' => 24000,
                'discount' => null,
                'active' => 1,
                'category_id' => 16,
                'status' => 1,
                'paid' => 0,
                'lat' => '47.6062',
                'lng' => '-122.3321',
                'verified_at' => Carbon::now(),
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'user_id' => 1,
                'city_id' => 1,
                'area_id' => 1,
                'image' => 'subaru_outback.jpg',
            ],
        ]);
    }
}
